export { default as menu } from "./menu.svg";
export { default as car } from "./car.png";
export { default as puzl } from "./puzl.png";
export { default as partners } from "./partners.png";
export { default as play } from "./play.svg";
export { default as mail } from "./mail.svg";
export { default as phone } from "./phone.svg";
export { default as point } from "./point.svg";
export { default as logo } from "./LogoPilot.png";